name: CI/CD using CML

on:
  push:
    branches: [ "main" ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12.13'

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Install Dependencies
        run: |
          pip install poetry
           poetry install

      - name: Train and Evaluate Model
        run: |
          poetry run python train.py

      - name: Generate CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Student Risk Prediction Results" > report.md
          echo "## Model Performance Metrics" >> report.md
          echo "![](./plots/confusion_matrix_2013.png)" >> report.md
          cml comment create report.md

      - name: Build Docker Image
        run: |
          docker build -t post-pandemic-box-office.

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 post-pandemic-box-office
